### ISSUE TITLE
Autowiring Support

### ISSUE THREAD

**Issue by ocxyz** [jsoumelidis/zend-sf-di-config#1]
Is there going to be a support for autowiring in the future?

Thanks.

**Comment by jsoumelidis** [comment]
Hi there, the short answer is “no”.
This library is a tool to convert a Zend Service Manager configuration array to a PSR-11-compatible Symfony DI Container· actually a Symfony DI ContainerBuilder object which IS already capable of doing all the autowiring stuff you are looking for.
I suggest you should take a look again on the docs of the Symfony DI Component for more information.

**Comment by ocxyz** [comment]
@jsoumelidis 
Sorry, I understand this is just a bridge for Zend Service Manager.
I was talking about the configuration for `Symfony\Component\DependencyInjection\Definition`. 
Do you have an idea how to configure `autowired` / `autoconfigured` from the outside ?

**Comment by jsoumelidis** [comment]
I’m not really sure what you want to achieve. If you could give me more details maybe I could give you more info.

**Comment by ocxyz** [comment]
Basically, the only way I know how to enable auto-wiring is to configure it through `Symfony\Component\DependencyInjection\Definition::autowire()` like so...

```php
<?php

// config/container.php

use JSoumelidis\SymfonyDI\Config\Config;
use JSoumelidis\SymfonyDI\Config\ContainerFactory;

$config  = require realpath(__DIR__) . '/config.php';
$factory = new ContainerFactory();

$container = $factory(new Config($config));

$container->autowire(App\Action\PingAction::class);
// or
// $container->getDefinition(App\Action\PingAction::class)->setAutowired(true);
// or
// $container->autowire('service_container');

return $container;
```
```php
<?php

namespace App\Action;

use ...;
use Psr\Container\ContainerInterface;

class PingAction implements MiddlewareInterface
{
    private $container;
    // I want a container instance here ...
    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler) : ResponseInterface
    {
        return new JsonResponse(['ack' => time()]);
    }
}
```

The above doesn't seem to work.

**Comment by jsoumelidis** [comment]
Hello again,
You can autowire a class using Symfony DI Component's ContainerBuilder like this:

`$container->autowire(App\Action\PingAction::class, App\Action\PingAction::class);`

First argument of the autowire() method is the service id (usually the FQDN of the class) and the second argument is the class itself.
