### ISSUE TITLE
Expressive compatibility

### ISSUE THREAD

**Issue by michalbundyra** [jsoumelidis/zend-sf-di-config#2]
Hello!

Just letting you know that we recently published container configuration documentation:
https://docs.zendframework.com/zend-expressive/v3/features/container/config/
We are working on library which covers all these cases and deliver common tests to check if the container is compatible and behave as expected, please see http://github.com/weierophinney/zend-container-config-test and the latest PR with tests updates:
https://github.com/weierophinney/zend-container-config-test/pull/4
We have already prepared fixed for Aura.Di and Pimple containers:
- zendframework/zend-auradi-config#10
- zendframework/zend-pimple-config#10

Would be nice if also this library is updated to use common tests. Please bare in mind it's still dev version, and the structure can be changes, but I think at this point we have quite good coverage of the desired behaviour.

**Comment by jsoumelidis** [comment]
Hello,
I have updated the code to use the tests provided by [zend-container-config-test](http://github.com/weierophinney/zend-container-config-test).
The only thing to notice is the lack of support for closures and objects as factories/delegators.
Symfony DI Component has not been designed to handle those cases as it's ability to compile (optimize) the configuration and cache the compiled container is a core feature (closures and objects cannot be cached).
Nevertheless, I found a workaround to exclude unsupported data sets from the test suite.
